In [1]:
import pandas as pd

In [2]:
hr_data = pd.read_csv('HR_comma_sep.csv')

In [9]:
hr_data.rename(columns={'sales':'dept'},inplace=True)

In [11]:
hr_data.dept.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le = LabelEncoder()

In [14]:
hr_data['dept'] = le.fit_transform(hr_data['dept'])

In [19]:
hr_data.dept.unique()

array([7, 2, 3, 9, 8, 4, 0, 6, 5, 1], dtype=int64)

In [20]:
hr_data['salary'] = le.fit_transform(hr_data['salary'])

In [21]:
hr_data

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,dept,salary
0,0.38,0.53,2,157,3,0,1,0,7,1
1,0.80,0.86,5,262,6,0,1,0,7,2
2,0.11,0.88,7,272,4,0,1,0,7,2
3,0.72,0.87,5,223,5,0,1,0,7,1
4,0.37,0.52,2,159,3,0,1,0,7,1
5,0.41,0.50,2,153,3,0,1,0,7,1
6,0.10,0.77,6,247,4,0,1,0,7,1
7,0.92,0.85,5,259,5,0,1,0,7,1
8,0.89,1.00,5,224,5,0,1,0,7,1
9,0.42,0.53,2,142,3,0,1,0,7,1
10,0.45,0.54,2,135,3,0,1,0,7,1
11,0.11,0.81,6,305,4,0,1,0,7,1
12,0.84,0.92,4,234,5,0,1,0,7,1
13,0.41,0.55,2,148,3,0,1,0,7,1
14,0.36,0.56,2,137,3,0,1,0,7,1
15,0.38,0.54,2,143,3,0,1,0,7,1
16,0.45,0.47,2,160,3,0,1,0,7,1
17,0.78,0.99,4,255,6,0,1,0,7,1
18,0.45,0.51,2,160,3,1,1,1,7,1
19,0.76,0.89,5,262,5,0,1,0,7,1
20,0.11,0.83,6,282,4,0,1,0,7,1
21,0.38,0.55,2,147,3,0,1,0,7,1
22,0.09,0.95,6,304,4,0,1,0,7,1
23,0.46,0.57,2,139,3,0,1,0,7,1
24,0.40,0.53,2,158,3,0,1,0,7,1
25,0.89,0.92,5,242,5,0,1,0,7,1
26,0.82,0.87,4,239,5,0,1,0,7,1
27,0.40,0.49,2,135,3,0,1,0,7,1
28,0.41,0.46,2,128,3,0,1,0,2,1
29,0.38,0.50,2,132,3,0,1,0,2,1
...,...,...,...,...,...,...,...,...,...,...
14969,0.43,0.46,2,157,3,0,1,0,7,2
14970,0.78,0.93,4,225,5,0,1,0,7,2
14971,0.39,0.45,2,140,3,0,1,0,7,2
14972,0.11,0.97,6,310,4,0,1,0,2,2
14973,0.36,0.52,2,143,3,0,1,0,2,2
14974,0.36,0.54,2,153,3,0,1,0,2,2
14975,0.10,0.79,7,310,4,0,1,0,3,2
14976,0.40,0.47,2,136,3,0,1,0,3,2
14977,0.81,0.85,4,251,6,0,1,0,3,2
14978,0.40,0.47,2,144,3,0,1,0,3,2
14979,0.09,0.93,6,296,4,0,1,0,9,2
14980,0.76,0.89,5,238,5,0,1,0,9,0
14981,0.73,0.93,5,162,4,0,1,0,9,1
14982,0.38,0.49,2,137,3,0,1,0,9,2
14983,0.72,0.84,5,257,5,0,1,0,9,2
14984,0.40,0.56,2,148,3,0,1,0,9,2
14985,0.91,0.99,5,254,5,0,1,0,9,2
14986,0.85,0.85,4,247,6,0,1,0,9,1
14987,0.90,0.70,5,206,4,0,1,0,9,1
14988,0.46,0.55,2,145,3,0,1,0,9,1
14989,0.43,0.57,2,159,3,1,1,0,9,1
14990,0.89,0.88,5,228,5,1,1,0,8,1
14991,0.09,0.81,6,257,4,0,1,0,8,1
14992,0.40,0.48,2,155,3,0,1,0,8,1
14993,0.76,0.83,6,293,6,0,1,0,8,1
14994,0.40,0.57,2,151,3,0,1,0,8,1
14995,0.37,0.48,2,160,3,0,1,0,8,1
14996,0.37,0.53,2,143,3,0,1,0,8,1
14997,0.11,0.96,6,280,4,0,1,0,8,1
14998,0.37,0.52,2,158,3,0,1,0,8,1

### DictVectorizer

In [22]:
hr_data = pd.read_csv('HR_comma_sep.csv')

In [23]:
hr_data.rename(columns={'sales':'dept'},inplace=True)

In [26]:
from sklearn.feature_extraction import DictVectorizer

In [32]:
dv = DictVectorizer()

In [38]:
dv.fit_transform([{'loc':'Mumbai'},{'loc':'Delhi'},{'loc':'Delhi'}]).toarray()

array([[ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.]])

In [39]:
dv.feature_names_

['loc=Delhi', 'loc=Mumbai']