In [2]:
import pandas as pd
import numpy as np

nrows, ncols = 100000, 100
rng = np.random.RandomState(42)
df1, df2, df3, df4 = (pd.DataFrame(rng.rand(nrows, ncols))
                      for i in range(4))

In [4]:
%timeit df1 + df2 + df3 + df4

1 loop, best of 3: 234 ms per loop

In [5]:
%timeit pd.eval('df1 + df2 + df3 + df4')

1 loop, best of 3: 139 ms per loop

In [6]:
result2 = pd.eval('df1 < df2 <= df3 != df4')

In [9]:
df = pd.DataFrame(rng.rand(1000, 3), columns=['A', 'B', 'C'])
df.head()

#result2 = df.query('A < 0.5 and B < 0.5')

          A         B         C
0  0.099772  0.365763  0.422644
1  0.941930  0.160890  0.832411
2  0.692094  0.255150  0.668258
3  0.901389  0.718069  0.577554
4  0.944688  0.354645  0.494979

In [10]:
result2 = df.query('A < 0.5 and B < 0.5')

In [11]:
result2

            A         B         C
0    0.099772  0.365763  0.422644
5    0.372495  0.126174  0.624648
7    0.304463  0.087584  0.398856
24   0.409017  0.249659  0.913871
31   0.422093  0.147429  0.106137
35   0.140227  0.427936  0.737378
38   0.442374  0.475850  0.482277
43   0.371637  0.063108  0.717849
47   0.220527  0.277775  0.646638
50   0.033919  0.138513  0.215566
56   0.032419  0.324782  0.493491
58   0.368696  0.346112  0.536845
79   0.021717  0.343033  0.611805
91   0.264538  0.144658  0.161459
95   0.448956  0.406370  0.286016
100  0.477297  0.077669  0.503425
107  0.487390  0.477082  0.542578
111  0.320882  0.150324  0.587659
115  0.082781  0.095136  0.924002
120  0.435150  0.395911  0.332889
124  0.109334  0.479377  0.956934
136  0.342996  0.100223  0.752956
139  0.312157  0.418157  0.743366
149  0.430057  0.381796  0.218506
154  0.054519  0.047882  0.228623
157  0.179657  0.290495  0.026084
159  0.104175  0.111907  0.892197
165  0.281108  0.251058  0.614648
170  0.293886  0.319715  0.725325
179  0.071502  0.115387  0.338977
..        ...       ...       ...
905  0.254599  0.069018  0.758259
907  0.032013  0.320798  0.967821
909  0.191003  0.328462  0.073021
911  0.048454  0.036364  0.274217
914  0.123950  0.131494  0.634189
920  0.473935  0.011241  0.616121
923  0.265404  0.258581  0.579934
928  0.003605  0.122749  0.720782
929  0.071860  0.371231  0.487616
931  0.446952  0.020049  0.426810
933  0.039206  0.007364  0.809410
935  0.334734  0.430758  0.087021
940  0.375543  0.422232  0.733710
945  0.464399  0.216987  0.158607
946  0.418082  0.330785  0.630971
947  0.196460  0.197426  0.854829
950  0.137644  0.027738  0.096586
955  0.331955  0.129682  0.055820
958  0.209879  0.134687  0.288384
964  0.047934  0.420268  0.018474
967  0.186655  0.380027  0.055160
968  0.192905  0.379252  0.823984
971  0.324987  0.115884  0.338702
975  0.451372  0.113358  0.753347
976  0.121897  0.235959  0.687000
985  0.490021  0.355504  0.502268
987  0.250296  0.391466  0.108348
990  0.364400  0.297859  0.461036
994  0.404296  0.314461  0.505974
998  0.157618  0.393238  0.154573

[239 rows x 3 columns]